# Generated by Django 5.1.5 on 2025-05-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigoPostal',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numInt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
