# Generated by Django 5.1.5 on 2025-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
