# Generated by Django 5.1.5 on 2025-06-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagen_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipoArticulo',
            field=models.CharField(choices=[('PDT', 'Producto'), ('SRV', 'Servicio')], default='PDT', max_length=3),
        ),
    ]
