# Generated by Django 5.1.5 on 2025-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_perfil_codigopostal_alter_perfil_numint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipoCuenta',
            field=models.CharField(choices=[('CLI', 'Cliente'), ('PRO', 'Proveedor'), ('EMP', 'Empleado')], default='CLI', max_length=3),
        ),
    ]
