# Generated by Django 5.1.5 on 2025-06-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria_tipoarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passwordcuentaespecial',
            name='passwordVisible',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
