# Generated by Django 5.1.5 on 2025-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_perfil_telefono_alter_perfil_tipocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numExt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
