# Generated by Django 5.1.5 on 2025-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_perfil_numext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='constanciaFiscal',
            field=models.FileField(blank=True, null=True, upload_to='constancias'),
        ),
    ]
