# Generated by Django 5.1.5 on 2025-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_perfil_constanciafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcuentaespecial',
            name='passwordVisible',
            field=models.CharField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordcuentaespecial',
            name='cuentaValidada',
            field=models.CharField(choices=[('PRO', 'Proveedor'), ('EMP', 'Empleado')], default='EMP', max_length=3),
        ),
        migrations.AlterField(
            model_name='passwordcuentaespecial',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
