# Generated by Django 5.1.5 on 2025-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_passwordcuentaespecial_passwordvisible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcuentaespecial',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
