# Generated by Django 5.1.5 on 2025-05-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_passwordcuentaespecial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('claveUnidad', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=300)),
                ('descripcion', models.TextField(default='')),
                ('claveFiscal', models.CharField(blank=True, default='', max_length=8)),
                ('tipoArticulo', models.CharField(choices=[('PDT', 'Producto'), ('SRV', 'Servicio')], default='PDT', max_length=3)),
                ('valorUnitario', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.categoria')),
                ('claveUnidad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='imagenes')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articulo')),
            ],
        ),
    ]
